<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@yield('title', 'HRIMS Notification')</title>
</head>
<body style="margin:0;padding:0;background-color:#ffffff;font-family:Arial,Helvetica,sans-serif;color:#000000;font-size:14px;line-height:1.55;-webkit-text-size-adjust:100%;">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" bgcolor="#ffffff" style="background-color:#ffffff;border-collapse:collapse;">
        <tr>
            <td align="center" style="padding:24px 16px;">
                <table role="presentation" width="640" cellpadding="0" cellspacing="0" border="0" bgcolor="#ffffff" style="width:100%;max-width:640px;background-color:#ffffff;border-collapse:collapse;">
                    <tr>
                        <td align="center" style="padding:0 0 14px 0;font-family:Arial,Helvetica,sans-serif;font-size:22px;font-weight:700;color:#173d69;letter-spacing:0.4px;">
                            MINISTRY OF HUMAN RIGHTS
                        </td>
                    </tr>
                    <tr>
                        <td bgcolor="#173d69" style="height:3px;line-height:3px;font-size:0;background-color:#173d69;">&nbsp;</td>
                    </tr>
                    <tr>
                        <td style="padding:22px 0 0 0;font-family:Arial,Helvetica,sans-serif;color:#000000;font-size:14px;line-height:1.55;">
                            @yield('content')
                        </td>
                    </tr>
                    <tr>
                        <td style="padding:28px 0 8px 0;font-family:Arial,Helvetica,sans-serif;color:#000000;font-size:14px;line-height:1.55;">
                            Regards,<br><br>
                            <strong>Data Collection &amp; Coordination Unit</strong><br>
                            Ministry of Human Rights<br>
                            Government of Pakistan
                        </td>
                    </tr>
                    <tr>
                        <td style="padding:16px 0 0 0;font-family:Arial,Helvetica,sans-serif;font-size:12px;font-style:italic;color:#555555;line-height:1.45;">
                            Automated notification: This email is generated by the Ministry of Human Rights data collection system. Please do not reply if this mailbox is unmonitored.
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</body>
</html>
